title: "35% Campaign"
email: 35percentelephant@gmail.com
timezone: UTC
url: 'https://35percent.github.io/newblog'
baseurl: "/newblog"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Jerry
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-12805041-5

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: 35percentelephant@gmail.com
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: 35percentelephant@gmail.com 
    description: "This is the author box. Write a short description of the author here."

collections:
    estates:
     output: true        

# Social
social:
  instagram: 
  facebook: 
  twitter: https://twitter.com/35percent_EAN

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-redirect-from
